language: go
sudo: false
go:
  - 1.11.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/weather-darwin-amd64
          - cross/weather-darwin-amd64.md5
          - cross/weather-darwin-amd64.sha256
          - cross/weather-darwin-386
          - cross/weather-darwin-386.md5
          - cross/weather-darwin-386.sha256
          - cross/weather-freebsd-amd64
          - cross/weather-freebsd-amd64.md5
          - cross/weather-freebsd-amd64.sha256
          - cross/weather-freebsd-386
          - cross/weather-freebsd-386.md5
          - cross/weather-freebsd-386.sha256
          - cross/weather-linux-arm
          - cross/weather-linux-arm.md5
          - cross/weather-linux-arm.sha256
          - cross/weather-linux-arm64
          - cross/weather-linux-arm64.md5
          - cross/weather-linux-arm64.sha256
          - cross/weather-linux-amd64
          - cross/weather-linux-amd64.md5
          - cross/weather-linux-amd64.sha256
          - cross/weather-linux-386
          - cross/weather-linux-386.md5
          - cross/weather-linux-386.sha256
          - cross/weather-solaris-amd64
          - cross/weather-solaris-amd64.md5
          - cross/weather-solaris-amd64.sha256
          - cross/weather-windows-amd64
          - cross/weather-windows-amd64.md5
          - cross/weather-windows-amd64.sha256
          - cross/weather-windows-386
          - cross/weather-windows-386.md5
          - cross/weather-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "KNVgaqBYuaiklqisi0LtLxd9F6ljClNomwfM7FsAXgpmdjQ5mJY4UNQmgw7O1hwehsoqs8FGaLyg527iMPjKIY5P8Tzg6QdORKxzmVaI1tExuwLbyKnSJB6HU+qkibHoGGtpS4fgsSsk2whUtxH3TcPNjO7PldtQW5R7cQBkINypvcipFeAcNWtNdcg+7lbgDW2hPz8apHBP1omTYymIi7/0YFiGJEerxYwTt4ou2Os8NHwLKakgQ/gL9oenWFTDLTxkQxScVKAss4m48r16W9KG2E/5r2MxGYKB4xxMbJHUE6ApPCpd6gEgy+JCIIc5p3719uN2CkiTnJXjKeZ3x/AW0WrYyPq1jT28gtPb53CmgDyUd74FRHblIX6fwEMmzzXJcZlpKI8OgPXo5tyAY7vZWTZQKs3nssl3wLX4+w9VSShh35jhB/dhkdeYDShi3sDc3zWUZPc/rsBzhzQM1f9SgST44fjSi0mHjpSU5tdPrvfeK9sBots7y7MwdQ7MjiH0B5wtjpSD6lugxWgKH5EwyGM1T5NNawDCtgKGs/Qpk/q2qG/+KmxpdWijYelP4E42I+xfy0xTNDG2Foz1x/LGFzjtklyR3Sdz46MDCeB2+MZzNjNxOQI9risNit0Qf799bJLggQ76QI7BvAic34lYLnB5erXoxuYzoKOJVKc="
